# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-31 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('kind', models.CharField(choices=[('today', 'today'), ('week', 'week'), ('month', 'month')], max_length=50)),
                ('sold', models.BooleanField(default=False)),
            ],
        ),
    ]
