# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-31 14:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171031_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 31, 20, 28, 16, 926233)),
        ),
    ]
